name: test_nextclade
on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  run_cwl_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]    
    steps:
      - uses: actions/checkout@v2
      - run: python --version
      - run: pip --version
      - run: pip install wheel
      - run: pip install cwltool cwltest
      - run: docker --version
      - run: cwltest --tool cwltool --test tests.yml
